Revert the "fix" on type mismatch errors on keys
The commit cc81f17c6c06a286b6e8b05ff83190f8c044dc49 changed the expected
type of the `_id` fields from a plain string to `six.text_type`. This
means that on Python 2, the `_id` fields will expect unicode
types. However, the keys of the objects actually have the type
`str`. With the change in the said commit, the following code fails:

>>> u = User.objects.get(name='test')
>>> r = Role()
>>> r.user_id = u.key
ValidationError: Assigned object's (user_id) type (str) does not matches to "unicode None"

The said change fails the test `test_set_rel_by_id`.